added docker
BlueVioletTeti/bookstore pull request #11
Opened 2023-10-13 13:38 UTC by BlueVioletTeti

2023-10-16 10:31 UTC, Denis-Balako approved these changes
Great! Left few optional suggestions.

2023-10-16 10:31 UTC, Denis-Balako commented on Dockerfile
> +#Final stage
Remove unnecessary comments

2023-10-16 10:31 UTC, Denis-Balako commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
Remove unnecessary comments

2023-10-16 10:31 UTC, Denis-Balako commented on src/test/java/com/vozniuk/bookstore/BookstoreApplicationTests.java
Remove unnecessary comments

2023-10-19 10:36 UTC, andrii-hoienko requested changes
Please remove unnecessary comments

2023-10-19 10:36 UTC, andrii-hoienko commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/books_app?serverTimezone=UTC
Is it possible to remove unnecessary comments?

2023-11-01 14:43 UTC, andrii-hoienko approved these changes
GJ!

2023-11-08 21:25 UTC, merged