added data validation and global exception handler
BlueVioletTeti/bookstore pull request #4
Opened 2023-09-10 22:04 UTC by BlueVioletTeti

2023-09-11 05:54 UTC, OlegTuryk commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private String isbn;
you can use ISBN annotation

2023-09-11 05:54 UTC, OlegTuryk approved these changes

2023-09-11 14:16 UTC, vovasalyha requested changes
GJ. Let's improve it a bit

2023-09-11 14:16 UTC, vovasalyha commented on pom.xml
> +			<groupId>org.hibernate.validator</groupId>
In Spring Boot it's better to choose starters over concrete dependencies, so I suggest to use validation starter

2023-09-11 14:16 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private String title;
Validate the size of title to not allow empty titles and to not exceed the maximum size set by DB schema, the same for author field

2023-09-11 14:16 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
>      private String isbn;
isbn has other validation rule except of not null (see Oleg's suggestion)

2023-09-11 14:16 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/exceptions/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
Usually invalid arguments it's 422 response code. Also, define the common response format for the application and create a class with exception response body.

2023-09-13 07:08 UTC, nacenik approved these changes
LGTM! 👍

2023-09-28 09:26 UTC, merged