added pagination and api annotations
BlueVioletTeti/bookstore pull request #5
Opened 2023-09-11 12:27 UTC by BlueVioletTeti

2023-09-11 21:27 UTC, holsoni approved these changes
LGTM!

2023-09-12 07:12 UTC, nacenik requested changes
Good solution, let's improve it a little bit :)

2023-09-12 07:12 UTC, nacenik commented on pom.xml
> +			<version>3.1.3</version>
do you really need a version here?

2023-09-12 07:12 UTC, nacenik commented on pom.xml
> +			<version>2.2.0</version>
put this as variable inside properties

2023-09-13 06:57 UTC, nacenik approved these changes
LGTM! 👍

2023-09-28 10:51 UTC, merged